<!--
  Copyright JS Foundation and other contributors, http://js.foundation

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<script type="text/x-red" data-help-name="catch">
  <p>攔截同一分頁上的節點所拋出的錯誤。</p>
  <h3>輸出</h3>
  <dl class="message-properties">
      <dt>error.message <span class="property-type">字串</span></dt>
      <dd>錯誤訊息。</dd>
      <dt>error.source.id <span class="property-type">字串</span></dt>
      <dd>拋出錯誤的節點的ID。</dd>
      <dt>error.source.type <span class="property-type">字串</span></dt>
      <dd>拋出錯誤的節點的類型。</dd>
      <dt>error.source.name <span class="property-type">字串</span></dt>
      <dd>拋出錯誤的節點的名稱。（如果已設定）</dd>
  </dl>
  <h3>詳細</h3>
  <p>如果某個節點在處理訊息時抛出錯誤，通常會導致流程終止執行。此節點可用於捕獲那些錯誤並執行例外處理流程。</p>
  <p>預設情況下，該節點將攔截同一分頁上所有節點所抛出的錯誤。或者，它可以針對特定節點，或設定爲僅攔截另一個 catch 節點未攔截到的錯誤。</p>
  <p>當錯誤發生時，所有符合攔截條件的 catch 節點都會收到錯誤訊息。</p>
  <p>如果在子流程中發送了錯誤，則該錯誤將由子流程中的任意 catch 節點處理。如果子流程中不存在 catch 節點，則那錯誤將被導向到子流程實例所在的分頁。</p>
  <p>如果訊息已經具有<code>error</code>屬性，則將該<code>error</code>複制爲<code>_error</code>。</p>
</script>
